// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjuTa2lih2vZyBU7ePpHNB9D_5F9UJMY0',
    appId: '1:768791123044:web:81db3e4cf0673f6bf73b71',
    messagingSenderId: '768791123044',
    projectId: 'decoder-a86d1',
    authDomain: 'decoder-a86d1.firebaseapp.com',
    storageBucket: 'decoder-a86d1.appspot.com',
    measurementId: 'G-FVTRVZLV7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXvVU3BFmik4Ty8gZ1P3rGMA21OaJ7xbg',
    appId: '1:768791123044:android:894897707792b02cf73b71',
    messagingSenderId: '768791123044',
    projectId: 'decoder-a86d1',
    storageBucket: 'decoder-a86d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHMn_9IM2e50qaeaTzVoyCMAroozsXl-0',
    appId: '1:768791123044:ios:a86f2c35e78fb38df73b71',
    messagingSenderId: '768791123044',
    projectId: 'decoder-a86d1',
    storageBucket: 'decoder-a86d1.appspot.com',
    iosBundleId: 'com.example.decoder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHMn_9IM2e50qaeaTzVoyCMAroozsXl-0',
    appId: '1:768791123044:ios:6aa1b8140e4e282df73b71',
    messagingSenderId: '768791123044',
    projectId: 'decoder-a86d1',
    storageBucket: 'decoder-a86d1.appspot.com',
    iosBundleId: 'com.example.decoder.RunnerTests',
  );
}
